- hosts: localhost
  gather_facts: False
  roles:
  - launch_ec2_instances
  tasks:
  - meta: refresh_inventory

- hosts: master_node:slave_nodes
  gather_facts: False
  roles:
  - configure-master-slave

- hosts: master_node
  gather_facts: False
  roles:
  - start-master
  tasks:
  - name: "Getting token from master"
    shell: "kubeadm token create --print-join-command"
    register: token
  - add_host:
      name: "token_for_worker"
      link: "{{ token['stdout'] }}"

- hosts: slave_nodes
  gather_facts: False
  tasks:
  - name: "Worker Nodes joining the cluster"
    shell: "{{ hostvars['token_for_worker']['link'] }}"

- hosts: master_node
  gather_facts: False
  roles:
  - wordpress-mysql
